set_property SRC_FILE_INFO {cfile:D:/RTL_PROJECTS/sine_wave/sine_wave.srcs/constrs_1/new/top.xdc rfile:../../../sine_wave.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11 [get_ports clk]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports rst]
